### PR TITLE
entrypoint cleanup + clipppy 

### PR DESCRIPTION
**Pull request by 0xNineteen**
- applied `cargo clippy --fix`
- cleaned up main.rs entrypoint 
- flatten shred sampler loop
  - reorg main logic into `get_shreds_and_leader_for_slot`
  - re-use this logic in both the `loop` and `pull_and_verify_shreds`

### CODE REVIEW

**Comment by anoushk1234** [comment]
@all-contributors please add @0xNineteen  for entrypoint cleanup + clippy

**Comment by anoushk1234** [comment]
@all-contributors please add @0xNineteen for code

**Comment by anoushk1234** [comment]
@all-contributors please add @0xNineteen for code

**Comment by anoushk1234** [comment]
Hey @0xNineteen thanks for open the pr, here's a few notes:

Can we please add error handling for not specifying path to archive shreds?
```sh
tinydancer start
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', tinydancer/src/tinydancer.rs:107:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Also there's an issue with the logger where it can't find the log file and just streams logs to the terminal
```sh
2023-03-22T07:12:48.459751Z  INFO tinydancer::sampler: Received empty    
2023-03-22T07:12:48.462115Z  INFO tinydancer::sampler: pull and verify true    

Slot 4292554 is Valid ✓
```
Also this error when starting client:
```sh
❯ tinydancer start "/tmp"
⠋ Initializing Client...2023-03-22T07:17:52.248095Z  INFO tinydancer::ui::ui: rendering ui    
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', tinydancer/src/sampler.rs:171:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(11), ...)', tinydancer/src/sampler.rs:113:30
thread 'main' panicked at 'error in sample service thread: JoinError::Panic(Id(9), ...)', tinydancer/src/tinydancer.rs:126:14
⠙ Monitoring Tinydancer: Actively Sampling Shreds 
```

**Comment by 0xNineteen** [comment]
fixed up all the comments

**Comment by anoushk1234** [comment]
@0xNineteen looks good, will merge! thanks for contributing ❤️

**Pull request merged**
